### ISSUE TITLE
can't find u.data file

### ISSUE THREAD

**Issue by thegoist** [tctctctctc/Matrix-Factorization#1]
https://github.com/tctctctctc/Matrix-Factorization/blob/020b0193a2a3fcc0b013de73bc29663e3fb940e5/MF/mf.py#L111

Hello, I am a college student. I am learning to use matrix factorization as a recommendation. I found that your code is very readable, and using pytorch speeds up the calculation and is easy to understand
At the beginning of the code, you should preprocess the data, and then separate the preprocessed data, but you did not give the preprocessed data here.
Could you please provide the preprocessed data, or provide the corresponding processing method?Thank you very much for your help

您好，我是一名在校大学生，我在学习使用矩阵分解做推荐，发现您的代码可读性很高，而且使用pytorch加速了计算且方便理解
在代码的开头，您应该是对数据进行了预处理，然后再对该预处理数据进行分离，但是这里预处理过后的数据您并没有给出。
请问，可否提供该预处理后的数据，或是提供相应的处理方法呢？真的非常感谢您的帮助

**Comment by tctctctctc** [comment]
您好，感谢关注！u.data是一个很小的数据集，仅仅作为测试代码能否运行的工具，后面将数据改成了常用的MovieLens，现已将代码目录更新。

**Comment by thegoist** [comment]
您好，十分感谢您提供的数据集以及代码，这对我帮助很大。star了
